# ZERO D ARRAY

In [1]:
import numpy as np

In [2]:
a=np.array(90)

In [3]:
print(a)

90


In [4]:
type(a)

numpy.ndarray

# ONE D ARRAY

In [5]:
b = np.array([1,2,34,4])
print(b)

[ 1  2 34  4]


In [6]:
print(b.ndim)

1


# 2D ARRAY

In [7]:
c = np.array([[1,2,3],[3,5,7]])
print(c)

[[1 2 3]
 [3 5 7]]


In [8]:
print(c.ndim)

2


# 3D ARRAY

In [11]:
d = np.array([[[1,2,3],[4,5,6]],[[2,3,7],[4,9,5]]]) #collection of 2d arrays
print(d)

[[[1 2 3]
  [4 5 6]]

 [[2 3 7]
  [4 9 5]]]


In [12]:
print(d.ndim)

3


# SHAPE AND RESHAPE

In [13]:
a = np.array([1,2,3,4])
print(a.shape)

(4,)


In [15]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)

(2, 4)


In [16]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = c.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
print(c.shape)

(12,)


In [18]:
print(new_arr.shape)

(4, 3)


In [19]:
new_arr2 = c.reshape(2,3,2)
print(new_arr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
print(new_arr2.shape)

(2, 3, 2)


In [21]:
arr = np.array([[1,2,3],[4,5,6]])
fla = arr.reshape(-1)
print(fla)

[1 2 3 4 5 6]


In [22]:
print(fla.shape)

(6,)


In [23]:
print(fla.ndim)

1


# Array Indexing

In [24]:
a = np.array([3,4,5,6])
print(a[0])

3


In [25]:
print(a[2])

5


In [26]:
print(a[2]+a[0])

8


In [27]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
print(b[1,4])

10


# Array iterating

In [29]:
arr = np.array([1,2,3])
for i in arr:
    print(i)

1
2
3


In [31]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [33]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


# Array slicing

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5])

[2 3 4 5]


In [36]:
print(a[2:7])

[3 4 5 6 7]


In [38]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
print(b[1,1:4])

[7 8 9]


In [40]:
print(b[0,0:3])

[1 2 3]


# Searching and Sorting numpy array

In [41]:
a = np.array([1,2,3,4,5,9,3,0,1,8])
x= np.where(a==1)
print(x)

(array([0, 8], dtype=int64),)


In [42]:
y=np.where(a==5)
print(y)

(array([4], dtype=int64),)


In [43]:
ans = np.where(a%2==0)
print(ans)

(array([1, 3, 7, 9], dtype=int64),)


In [44]:
print(np.sort(a))

[0 1 1 2 3 3 4 5 8 9]


In [45]:
a3 = np.array(["apple","chiku","banana"])
print(np.sort(a3))

['apple' 'banana' 'chiku']
